#!/usr/bin/env python3
"""Build the all-in-one "High Adventure" mod from the individual ha-* mods.

Merges each sibling mod's objects/, graphics/ and scripts_modactive/ trees into
./high-adventure/. Identical duplicate files (e.g. shaping_tree.png shipped by
both ha-high-elves and ha-playable-civs) are deduped; differing collisions abort
the build. Also runs an OBJECT-aware scan for raw definitions that appear twice
across the merged objects/ (a real merge conflict DF would reject or skip).

Re-run after bumping any member mod; then bump VERSION here when contents change.
"""

import filecmp
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'high-adventure'
MOD_ID = 'HIGH_ADVENTURE'
NAME = 'High Adventure'
NUMERIC_VERSION = 1
DISPLAYED_VERSION = '0.1'

# raw definition tokens that must be globally unique, per [OBJECT:x] file type
DEF_TOKENS = {
    'CREATURE': ['CREATURE'],
    'ENTITY': ['ENTITY'],
    'ITEM': ['ITEM_WEAPON', 'ITEM_ARMOR', 'ITEM_HELM', 'ITEM_GLOVES', 'ITEM_SHOES',
             'ITEM_PANTS', 'ITEM_SHIELD', 'ITEM_TOOL', 'ITEM_AMMO', 'ITEM_TOY',
             'ITEM_INSTRUMENT', 'ITEM_TRAPCOMP', 'ITEM_SIEGEAMMO', 'ITEM_FOOD'],
    'BUILDING': ['BUILDING_WORKSHOP', 'BUILDING_FURNACE'],
    'REACTION': ['REACTION'],
    'INTERACTION': ['INTERACTION'],
    'BODY': ['BODY', 'BODYGLOSS'],
    'BODY_DETAIL_PLAN': ['BODY_DETAIL_PLAN'],
    'MATERIAL_TEMPLATE': ['MATERIAL_TEMPLATE'],
    'TISSUE_TEMPLATE': ['TISSUE_TEMPLATE'],
    'CREATURE_VARIATION': ['CREATURE_VARIATION'],
    'PLANT': ['PLANT'],
    'LANGUAGE': ['TRANSLATION', 'SYMBOL', 'WORD'],
    'GRAPHICS': ['TILE_PAGE'],
}


def member_mods():
    return sorted(d for d in ROOT.iterdir()
                  if d.is_dir() and d != OUT and (d / 'info.txt').is_file())


def info_field(mod, field):
    m = re.search(r'\[' + field + r':([^\]]+)\]', (mod / 'info.txt').read_text())
    return m.group(1) if m else '?'


def merge_tree(src, dst, sources):
    for f in sorted(src.rglob('*')):
        if not f.is_file():
            continue
        rel = f.relative_to(src)
        target = dst / rel
        if target.exists():
            if filecmp.cmp(f, target, shallow=False):
                continue  # identical duplicate: keep the first copy
            sys.exit(f'COLLISION: {rel} differs between {sources[rel]} and {f}')
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(f, target)
        sources[rel] = f


def scan_duplicate_defs(objdir, subdirs):
    seen, dupes = {}, []
    for sub in subdirs:
        for f in sorted((objdir / sub).glob('*.txt')) if (objdir / sub).is_dir() else []:
            text = f.read_text(errors='replace')
            m = re.search(r'\[OBJECT:([A-Z_]+)\]', text)
            prefixes = DEF_TOKENS.get(m.group(1)) if m else None
            if not prefixes:
                continue
            pat = re.compile(r'^\s*\[(' + '|'.join(prefixes) + r'):([^\]:]+)\]', re.M)
            for tok, ident in pat.findall(text):
                key = f'{tok}:{ident}'
                if key in seen and seen[key] != f.name:
                    dupes.append(f'{key} in both {seen[key]} and {f.name}')
                seen.setdefault(key, f.name)
    return dupes


def main():
    mods = member_mods()
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir()
    sources = {}
    included = []
    for mod in mods:
        for sub in ('objects', 'graphics', 'scripts_modactive'):
            if (mod / sub).is_dir():
                merge_tree(mod / sub, OUT / sub, sources)
        included.append(f"{info_field(mod, 'NAME')} {info_field(mod, 'DISPLAYED_VERSION')}")
        print(f'  + {mod.name} ({included[-1]})')

    desc = ('The complete Dwarf Fortress: High Adventure suite as a single mod. '
            'Bundles: ' + '; '.join(included) + '. '
            'Enable EITHER this mod OR the individual HA mods in a world, never both '
            '(both at once duplicates every raw object). Generated by build-high-adventure.py.')
    (OUT / 'info.txt').write_text(
        f'[ID:{MOD_ID}]\n'
        f'[NUMERIC_VERSION:{NUMERIC_VERSION}]\n'
        f'[DISPLAYED_VERSION:{DISPLAYED_VERSION}]\n'
        f'[EARLIEST_COMPATIBLE_NUMERIC_VERSION:{NUMERIC_VERSION}]\n'
        f'[EARLIEST_COMPATIBLE_DISPLAYED_VERSION:{DISPLAYED_VERSION}]\n'
        f'[AUTHOR:High Adventure]\n'
        f'[NAME:{NAME}]\n'
        f'[DESCRIPTION:{desc}]\n')

    dupes = scan_duplicate_defs(OUT, ['objects', 'graphics'])
    for d in dupes:
        print(f'  WARNING duplicate definition: {d}')
    n = sum(1 for f in OUT.rglob('*') if f.is_file())
    print(f'built {OUT.name}: {len(mods)} mods, {n} files, {len(dupes)} duplicate defs')


if __name__ == '__main__':
    main()
