# Makefile — install the df-smooth-movement DFHack plugin.
#
# The submodule under other-authors/df-smooth-movement ships SOURCE ONLY, and that source only
# builds inside a full DFHack source tree (its CMakeLists uses DFHack's dfhack_plugin() macro —
# see the submodule README "Build" section). So there is no standalone source build here.
#
# `make install` downloads the prebuilt plugin binary matching your platform and DFHack version
# from the upstream GitHub release, verifies its SHA-256, and extracts it into DFHack's plugin
# directory. The plugin is auto-enabled by `magnus-scripts lovely`; `make enable` turns it on now.
#
# Common use:
#     make install                              # auto-detect everything
#     make install DFHACK_DIR=/path/to/DFHack   # if your DFHack lives elsewhere
#     make install DFHACK_VERSION=53.15-r2      # pin the release asset explicitly
#     make build                                # compile from the submodule SOURCE instead
#                                               # (clones the DFHack source tree into build/ on
#                                               # first run; use when the source has unreleased
#                                               # fixes). Restart DF after installing.
#
# Re-run after every DFHack update (plugins are ABI-specific to a DFHack version).

REPO           ?= notliad/df-smooth-movement
PLUGIN         ?= smooth-movement
# The DFHack install directory (the folder that contains hack/plugins/). Override if yours differs;
# on some setups DFHack lives inside the Dwarf Fortress folder instead of its own.
DFHACK_DIR     ?= $(HOME)/.local/share/Steam/steamapps/common/DFHack
# Which release to pull from: "latest" or a tag like v0.2.0.
RELEASE        ?= latest
# DFHack version the asset must match, e.g. 53.15-r2. Empty = auto-detect via dfhack-run when the
# game is running, else fall back to the sole platform asset in the release.
DFHACK_VERSION ?=

SHELL       := bash
.ONESHELL:
.SHELLFLAGS := -eu -o pipefail -c

UNAME_S := $(shell uname -s)
UNAME_M := $(shell uname -m)

DFRUN   := $(DFHACK_DIR)/dfhack-run
PLUGDIR := $(DFHACK_DIR)/hack/plugins
SO      := $(PLUGDIR)/$(PLUGIN).plug.so

# --- source build (make build) ---
# Everything lives under build/ (gitignored): the DFHack source tree, its cmake build dir, and a
# locally-built XML::LibXSLT (DFHack's codegen needs it; built from CPAN when the system perl
# lacks it, so no root is required).
ROOT        := $(abspath .)
BUILDDIR    := $(ROOT)/build
DFHACK_SRC  := $(BUILDDIR)/dfhack
CMAKE_BUILD := $(DFHACK_SRC)/build-rel
PERL5_LOCAL := $(BUILDDIR)/perl5
PLUGIN_SRC  := $(ROOT)/other-authors/df-smooth-movement
# Git tag of the DFHack source to build against. Must match the installed DFHack (ABI).
DFHACK_TAG  ?= 53.15-r2
JOBS        ?= $(shell nproc)

# --- README composition (make readme) ---
# README.md is GENERATED by concatenating these, in this order. Edit the parts, never README.md.
# BROKEN_FEATURES.md is deliberately NOT included: the README advertises what works.
README_PARTS := README-HEADER.md \
                FORTRESS_MODE_FEATURES.md \
                ADVENTURE_MODE_FEATURES.md \
                HIGH_ADVENTURE_FEATURES.md

.DEFAULT_GOAL := help
.PHONY: help install build enable disable status uninstall readme

help:
	@echo "df-smooth-movement plugin — make targets:"
	echo "  make install    download + checksum-verify the prebuilt plugin, install into DFHack"
	echo "  make build      compile the plugin from the submodule source (clones the DFHack"
	echo "                  source tree into build/ on first run) and install it. Restart DF after."
	echo "  make enable     load + enable it now (Dwarf Fortress must be running)"
	echo "  make disable    disable it now"
	echo "  make status     show the plugin's status / installed binary"
	echo "  make uninstall  remove the installed plugin binary"
	echo
	echo "Repo targets:"
	echo "  make readme     compose README.md from $(words $(README_PARTS)) part files (edit those, not README.md)"
	echo
	echo "Variables (override on the command line, e.g. make install DFHACK_DIR=...):"
	echo "  DFHACK_DIR      = $(DFHACK_DIR)"
	echo "  RELEASE         = $(RELEASE)"
	echo "  DFHACK_VERSION  = $(if $(DFHACK_VERSION),$(DFHACK_VERSION),(auto-detect))"
	echo "  REPO            = $(REPO)"

install:
	@platform=""
	case "$(UNAME_S)/$(UNAME_M)" in
	  Linux/x86_64) platform="linux-x86_64" ;;
	  *)
	    echo "No prebuilt binary for $(UNAME_S)/$(UNAME_M) (upstream ships linux-x86_64 and windows-x86_64)."
	    echo "Build from source inside a DFHack tree — see other-authors/df-smooth-movement/README.md."
	    exit 1 ;;
	esac
	if [ ! -d "$(PLUGDIR)" ]; then
	  echo "DFHack plugin dir not found: $(PLUGDIR)"
	  echo "Point DFHACK_DIR at your DFHack install (the folder containing hack/plugins/):"
	  echo "    make install DFHACK_DIR=/path/to/DFHack"
	  exit 1
	fi
	# Resolve the DFHack version to match against asset names.
	dfver="$(DFHACK_VERSION)"
	if [ -z "$$dfver" ] && [ -x "$(DFRUN)" ]; then
	  dfver="$$("$(DFRUN)" lua 'print(dfhack.getDFHackVersion())' 2>/dev/null | tr -d '\r' | grep -oE '^[0-9]+\.[0-9]+-r[0-9]+' || true)"
	  [ -n "$$dfver" ] && echo "Detected running DFHack $$dfver."
	fi
	# Fetch the release metadata (public repo; GITHUB_TOKEN used only if set, to dodge rate limits).
	if [ "$(RELEASE)" = "latest" ]; then api="https://api.github.com/repos/$(REPO)/releases/latest"; \
	else api="https://api.github.com/repos/$(REPO)/releases/tags/$(RELEASE)"; fi
	curlargs=(-fsSL -H "Accept: application/vnd.github+json")
	[ -n "$${GITHUB_TOKEN:-}" ] && curlargs+=(-H "Authorization: Bearer $$GITHUB_TOKEN")
	echo "Querying $$api"
	json="$$(curl "$${curlargs[@]}" "$$api")"
	urls="$$(printf '%s' "$$json" | grep -oE '"browser_download_url":[[:space:]]*"[^"]+"' | sed -E 's/.*"(https[^"]+)".*/\1/')"
	# Candidate = the platform tarball(s); narrow by DFHack version when we know it.
	cands="$$(printf '%s\n' "$$urls" | grep -E "$${platform}\.tar\.gz$$" || true)"
	if [ -n "$$dfver" ]; then
	  filtered="$$(printf '%s\n' "$$cands" | grep -F "dfhack$${dfver}-" || true)"
	  if [ -n "$$filtered" ]; then cands="$$filtered"; \
	  else echo "warning: release has no asset for DFHack $$dfver; using the available $$platform asset instead."; fi
	fi
	n="$$(printf '%s\n' "$$cands" | grep -c . || true)"
	if [ "$$n" -eq 0 ]; then
	  echo "No $$platform asset in the $(RELEASE) release. Available assets:"
	  printf '%s\n' "$$urls" | sed -E 's#.*/##'
	  exit 1
	fi
	if [ "$$n" -gt 1 ]; then
	  echo "Multiple $$platform assets — pick one with DFHACK_VERSION=<ver>:"
	  printf '  %s\n' $$(printf '%s\n' "$$cands" | sed -E 's#.*/##')
	  exit 1
	fi
	asset="$$cands"
	echo "Selected asset: $${asset##*/}"
	# Download, verify checksum, extract into the DFHack dir.
	tmp="$$(mktemp -d)"; trap 'rm -rf "$$tmp"' EXIT
	curl -fSL --progress-bar -o "$$tmp/p.tar.gz" "$$asset"
	if curl -fsSL -o "$$tmp/p.sha256" "$${asset}.sha256"; then
	  exp="$$(awk '{print $$1}' "$$tmp/p.sha256")"
	  act="$$(sha256sum "$$tmp/p.tar.gz" | awk '{print $$1}')"
	  if [ "$$exp" != "$$act" ]; then echo "CHECKSUM MISMATCH: got $$act, expected $$exp"; exit 1; fi
	  echo "Checksum OK ($$act)."
	else
	  echo "warning: no .sha256 published for this asset; skipping checksum verification."
	fi
	tar -C "$(DFHACK_DIR)" -xzf "$$tmp/p.tar.gz"
	if [ ! -f "$(SO)" ]; then echo "Extraction did not produce $(SO)"; exit 1; fi
	echo "Installed: $(SO)"
	# If DF is running, load+enable it right away; otherwise it loads on next launch.
	if [ -x "$(DFRUN)" ] && "$(DFRUN)" lua 'print(1)' >/dev/null 2>&1; then
	  "$(DFRUN)" load $(PLUGIN) >/dev/null 2>&1 || true
	  "$(DFRUN)" enable $(PLUGIN) || true
	  echo "Loaded and enabled in the running game."
	else
	  echo "Start Dwarf Fortress to load it. 'magnus-scripts lovely' enables it automatically,"
	  echo "or run 'make enable' while the game is running."
	fi

# Compile the plugin from the submodule source against a local DFHack source tree, then install.
# The tree is cloned (shallow, tag $(DFHACK_TAG), with submodules) into build/dfhack on first run;
# later runs reuse it. ABI rule: $(DFHACK_TAG) must match the installed DFHack version.
build:
	@if [ ! -f "$(PLUGIN_SRC)/CMakeLists.txt" ]; then
	  echo "Initializing the plugin submodule..."
	  git -C "$(ROOT)" submodule update --init other-authors/df-smooth-movement
	fi
	if [ ! -f "$(DFHACK_SRC)/CMakeLists.txt" ]; then
	  echo "Cloning the DFHack $(DFHACK_TAG) source tree (one-time, ~200MB)..."
	  git clone --depth 1 --branch "$(DFHACK_TAG)" --recurse-submodules --shallow-submodules -j8 \
	    https://github.com/DFHack/dfhack "$(DFHACK_SRC)"
	fi
	# DFHack's codegen needs perl XML::LibXSLT; build it locally (no root) if the system lacks it.
	export PERL5LIB="$(PERL5_LOCAL)/lib/perl5$${PERL5LIB:+:$$PERL5LIB}"
	if ! perl -MXML::LibXSLT -e 1 2>/dev/null; then
	  echo "Building perl XML::LibXSLT locally into build/perl5 (needs libxslt headers)..."
	  mkdir -p "$(BUILDDIR)/perl5-src"
	  cd "$(BUILDDIR)/perl5-src"
	  [ -f libxslt.tar.gz ] || curl -fsSL -o libxslt.tar.gz \
	    "https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXSLT-2.003000.tar.gz"
	  tar xzf libxslt.tar.gz && cd XML-LibXSLT-*
	  perl Makefile.PL INSTALL_BASE="$(PERL5_LOCAL)" >/dev/null && make -j4 >/dev/null && make install >/dev/null
	  perl -MXML::LibXSLT -e 1 || { echo "local XML::LibXSLT build failed"; exit 1; }
	fi
	# Wire the plugin into the tree as an external plugin (symlink -> always builds current source).
	mkdir -p "$(DFHACK_SRC)/plugins/external"
	ln -sfn "$(PLUGIN_SRC)" "$(DFHACK_SRC)/plugins/external/df-smooth-movement"
	grep -qs 'add_subdirectory(df-smooth-movement)' "$(DFHACK_SRC)/plugins/external/CMakeLists.txt" || \
	  echo 'add_subdirectory(df-smooth-movement)' >> "$(DFHACK_SRC)/plugins/external/CMakeLists.txt"
	if [ ! -f "$(CMAKE_BUILD)/CMakeCache.txt" ]; then
	  # -Wno-error goes in the per-config flags: they land AFTER DFHack's hardcoded -Werror on the
	  # compile line, neutralizing it (newer gcc releases add warnings the pinned tree predates).
	  cmake -S "$(DFHACK_SRC)" -B "$(CMAKE_BUILD)" -G Ninja \
	    -DCMAKE_BUILD_TYPE=Release -DBUILD_DOCS=OFF -DBUILD_TESTS=OFF \
	    -DCMAKE_CXX_FLAGS_RELEASE="-O2 -DNDEBUG -Wno-error" \
	    -DCMAKE_C_FLAGS_RELEASE="-O2 -DNDEBUG -Wno-error"
	fi
	cmake --build "$(CMAKE_BUILD)" --target $(PLUGIN) -j"$(JOBS)"
	built="$$(find "$(CMAKE_BUILD)" -name '$(PLUGIN).plug.so' | head -1)"
	[ -n "$$built" ] || { echo "build produced no $(PLUGIN).plug.so"; exit 1; }
	# Swap the binary in. If DF is running, unload the old plugin first so the file isn't in use;
	# a RESTART of Dwarf Fortress is still the reliable way to pick up the new code.
	if [ -x "$(DFRUN)" ] && "$(DFRUN)" lua 'print(1)' >/dev/null 2>&1; then
	  "$(DFRUN)" disable $(PLUGIN) >/dev/null 2>&1 || true
	  "$(DFRUN)" unload $(PLUGIN) >/dev/null 2>&1 || true
	fi
	cp -f "$$built" "$(SO)"
	echo "Installed freshly-built plugin: $(SO)"
	echo "RESTART Dwarf Fortress now (or: dfhack-run load $(PLUGIN) && dfhack-run enable $(PLUGIN)"
	echo "for a hot reload, then verify with 'make status')."

enable:
	@"$(DFRUN)" load $(PLUGIN) >/dev/null 2>&1 || true
	"$(DFRUN)" enable $(PLUGIN)

disable:
	@"$(DFRUN)" disable $(PLUGIN)

status:
	@"$(DFRUN)" $(PLUGIN) 2>/dev/null || { \
	  echo "Could not query the plugin (is Dwarf Fortress running?). Installed binary:"; \
	  ls -l "$(SO)" 2>/dev/null || echo "  (not installed — run 'make install')"; }

uninstall:
	@rm -fv "$(SO)"

# Concatenate the part files into README.md. Written to a temp file and moved into place, so a
# missing part cannot leave a half-built README behind.
readme:
	@missing=""
	for f in $(README_PARTS); do
	  [ -f "$$f" ] || missing="$$missing $$f"
	done
	if [ -n "$$missing" ]; then
	  echo "make readme: missing part file(s):$$missing"
	  exit 1
	fi
	tmp="$$(mktemp README.md.XXXXXX)"
	trap 'rm -f "$$tmp"' EXIT
	for f in $(README_PARTS); do
	  cat "$$f" >> "$$tmp"
	  printf '\n' >> "$$tmp"
	done
	mv "$$tmp"  README.md
	trap - EXIT
	echo "README.md composed from $(words $(README_PARTS)) parts:"
	for f in $(README_PARTS); do printf '  %s (%s lines)\n' "$$f" "$$(wc -l < "$$f")"; done
