-- Show the selected creature's description in a scrollable panel, bottom-left.
--@module = true
--[[
When a creature is selected (its unit sheet is open), this shows the creature's
description -- `caste.description` -- in a wrapping, scrollable block in the
bottom-left. Most useful for forgotten beasts / titans / generated creatures,
whose description is their full generated flavor (body, materials, special
attacks). For ordinary creatures it's the species blurb. Shows on the unit
sheet in BOTH fortress mode and adventure mode (dungeonmode).

Registered automatically as overlay `creature-description.desc`.
Reposition with `gui/overlay`.
]]

local overlay = require('plugins.overlay')
local widgets = require('gui.widgets')
local gui = require('gui')

-- ---- kill summary -----------------------------------------------------------
-- Expands "Kills: N" into notable categories, in this order:
--   demons, archangels (a vault's colossal guardian), angels, each MEGABEAST TYPE ("2 dragons, 1 bronze colossus, 1
--   forgotten beast" -- generated FB races all share a name, so they pool),
--   each semi-megabeast type ("1 giant, 1 cyclops"), VAMPIRES then NECROMANCERS
--   (each by creature type -- "1 goblin vampire, 2 human necromancers"), undead,
--   each WERECREATURE by its beast form ("1 weremoose") -- all of them ahead of
--   the ordinary sentient kills, since the victim's BIRTH race would otherwise
--   report the weremoose as "1 goblin" -- then every sentient kill (anything that
--   can learn or speak) grouped by CASTE NAME -- the natural key: gender castes
--   share their name ("goblin"), while special castes carry their own
--   ("ulitharid", "ancient dragon", "drider") -- most kills first, then <the
--   largest animal species killed>, other
-- e.g. "66 kills: 1 demon, 2 dragons, 1 goblin vampire, 2 kobold necromancers,
--       4 undead, 1 weremoose, 30 goblins, 9 illithids, 10 giant elephants, 9 other"

-- adult size that separates a vault guardian ("archangel") from a rank-and-file angel
local ARCHANGEL_SIZE = 100000

-- special category for a race, or nil for the sentient/animal/other pools
local function classify_race(rid)
    local cr = df.global.world.raws.creatures.all[rid]
    if not cr then return nil end
    local id = tostring(cr.creature_id)
    local f = cr.caste[0] and cr.caste[0].flags
    -- angels have no caste flag of their own; their generated tokens carry DIVINE
    -- ("HF133 DIVINE_1"). ANGEL is accepted too for modded ones, but only when the race
    -- is not a natural animal -- vanilla SHARK_ANGEL is the angelshark, a fish.
    if id:find('DIVINE') or (id:find('ANGEL') and not (f and f.NATURAL_ANIMAL)) then
        -- DF generates three divine races per deity, and the third is the vault's
        -- colossal guardian: same tokens, but an adult size two orders of magnitude
        -- above its siblings (1,000,000 vs the 6-9k of a humanoid angel). Size is the
        -- distinction, not the trailing numeral, which nothing guarantees is ordered.
        local c = cr.caste[0]
        if c and (c.misc.adult_size or 0) >= ARCHANGEL_SIZE then return 'archangel' end
        return 'angel'
    end
    if f then
        if f.DEMON or f.UNIQUE_DEMON then return 'demon' end
        if f.MEGABEAST or f.TITAN or f.FEATURE_BEAST then return 'megabeast' end
        if f.SEMIMEGABEAST then return 'beast' end
    end
    return nil
end

-- is this race a (non-speaking, non-learning) animal, and its adult body size
local function animal_info(rid)
    local cr = df.global.world.raws.creatures.all[rid]
    local c = cr and cr.caste[0]
    if not c then return false, 0 end
    if c.flags.CAN_LEARN or c.flags.CAN_SPEAK then return false, 0 end
    return true, c.misc.adult_size or 0
end

local CAT_PLURAL = {demon = 'demons', archangel = 'archangels', angel = 'angels'}

-- WERECREATURES and VAMPIRES are recorded as a CURSE on the historical figure, never as a race:
-- the figure keeps its BIRTH race, so the weremoose that killed your dwarves is stored as the
-- goblin it used to be and would be counted as "1 goblin". Nothing on the victim says otherwise --
-- its `curse.race` is still the goblin, and `curse.name` is empty for werebeasts (the named ones
-- like "necromancer" or the procedural "death stalker" / "bitter corpse" are other curses).
--
-- What DOES say so is the curse's INTERACTIONS: each interaction effect is stamped with an
-- `arena_name` naming the kind of curse -- "Werebeast", "Vampire", "Necromancer". That stamp is
-- generated by DF along with the curse, so it holds for procedurally-named curses and for mods,
-- and needs no string matching against display names.
--
-- Only NAMED victims can be classified this way: an anonymous kill group carries a race and caste
-- but no figure, so there is no curse to read. Werebeasts and vampires are always historical
-- figures, so in practice that costs nothing.
local function cursed_as(hf, arena_name)
    local c = hf and hf.info and hf.info.curse
    if not c then return nil end
    for _, inter in ipairs(c.active_interactions) do
        local ok, effects = pcall(function() return inter.effects end)
        if ok and effects then
            for _, ef in ipairs(effects) do
                local okn, an = pcall(function() return ef.arena_name end)
                if okn and an == arena_name then return ef end
            end
        end
    end
end

-- The beast form's name, from the curse's BODY_TRANSFORMATION effect. That effect names the race
-- it turns you into (race_str "NIGHT_CREATURE_42"), and THAT race is the one actually called
-- "weremoose" -- the werebeast races are all NIGHT_CREATURE_n tokens, so their token tells you
-- nothing and only the display name does. Returns singular, plural.
local function were_form_name(ef)
    local ok, syns = pcall(function() return ef.creature_interaction.syndrome end)
    if not (ok and syns) then return nil end
    for _, syn in ipairs(syns) do
        for _, ce in ipairs(syn.ce) do
            if ce:getType() == df.creature_interaction_effect_type.BODY_TRANSFORMATION then
                local okr, races = pcall(function() return ce.race end)
                if okr and races and #races > 0 then
                    local cr = df.global.world.raws.creatures.all[races[0]]
                    if cr then return tostring(cr.name[0]), tostring(cr.name[1]) end
                end
            end
        end
    end
end

-- `cursed_as(hf, 'Werebeast')` alone MISSES bite-infected werebeasts: DF stamps arena_name on
-- the ROOT curse interaction (e.g. "DEITY_CURSE_WEREBEAST_moose_1") but leaves it BLANK on the
-- secondary interaction generated when that weremoose's bite infects someone new
-- ("..._moose_1_BITE") -- confirmed live (2026-08) against a bitten weremoose CHILD victim:
-- arena_name == '', while the SAME effect's nested syndrome still carries the
-- BODY_TRANSFORMATION untouched. Since a bite chain is exactly how most werebeast kills happen
-- (the original is rare; everyone it infects isn't), that blank silently miscounted every one of
-- them under the victim's birth race instead of "weremoose". So look for the BODY_TRANSFORMATION
-- structurally instead of trusting arena_name: it is present on both variants, and no other curse
-- kind (Vampire, Necromancer) changes the victim's body, so its presence alone identifies a
-- werebeast. Returns the effect (for were_form_name) or nil.
local function were_effect(hf)
    local c = hf and hf.info and hf.info.curse
    if not c then return nil end
    for _, inter in ipairs(c.active_interactions) do
        local ok, effects = pcall(function() return inter.effects end)
        if ok and effects then
            for _, ef in ipairs(effects) do
                local ok2, syns = pcall(function() return ef.creature_interaction.syndrome end)
                if ok2 and syns then
                    for _, syn in ipairs(syns) do
                        for _, ce in ipairs(syn.ce) do
                            if ce:getType() == df.creature_interaction_effect_type.BODY_TRANSFORMATION then
                                return ef
                            end
                        end
                    end
                end
            end
        end
    end
end

-- "goblin vampire" / "human necromancer": the victim's BIRTH race in front of the curse, so each
-- creature type counts separately. The race word is an adjective here, so the plural pluralises
-- the curse and not the race -- "goblin vampires", never "goblins vampires". The curse's own
-- display name is deliberately not used: it is procedural ("death stalker") and empty as often as
-- not, and the point is to tell a goblin vampire from a human one.
local function cursed_label(rid, word)
    local cr = df.global.world.raws.creatures.all[rid]
    local race = cr and tostring(cr.name[0]) or ''
    if race == '' then return word, word .. 's' end
    return race .. ' ' .. word, race .. ' ' .. word .. 's'
end

-- any set bit in a kill group's undead_flags (zombie, ghostly, or the unnamed variants)
-- means the whole group was undead
local function is_undead_group(uf)
    if not uf then return false end
    for _, v in pairs(uf) do
        if v == true then return true end
    end
    return false
end

-- "310 kills: 139 goblins, 46 elves, ... 12 other" (or "Kills: 0").
-- Module-public so other scripts (and tests) can reuse it.
-- append {n, sing, plur} counts into a name-keyed group table. Keying on the
-- DISPLAY name pools what should pool: every generated forgotten-beast race
-- shares a name, as do a race's gender castes, as do the KOBOLD/HA_KOBOLD twins.
local function bump(groups, key_sing, key_plur, n)
    local g = groups[key_plur]
    if not g then
        g = {n = 0, sing = key_sing, plur = key_plur}
        groups[key_plur] = g
    end
    g.n = g.n + n
end

-- most kills first, name breaks ties; returns the sorted list
local function sorted_groups(groups)
    local list = {}
    for _, g in pairs(groups) do list[#list + 1] = g end
    table.sort(list, function(a, b)
        if a.n ~= b.n then return a.n > b.n end
        return a.plur < b.plur
    end)
    return list
end

function kill_summary(u)
    local hf = u.hist_figure_id and u.hist_figure_id >= 0 and df.historical_figure.find(u.hist_figure_id)
    if not (hf and hf.info and hf.info.kills) then return 'Kills: 0' end
    local k = hf.info.kills
    -- cats: pooled demon/angel/undead counters; megas/beasts/sentients: name-keyed
    local cats, megas, beasts, weres, vamps, necros, sentients, animals =
        {}, {}, {}, {}, {}, {}, {}, {}
    local other, total = 0, 0
    local function add(rid, caste, n, undead, vhf)
        total = total + n
        -- undead trump every other category: a skeletal elf counts as undead, not elf
        if undead then
            cats.undead = (cats.undead or 0) + n
            return
        end
        -- ...and a curse trumps the victim's birth race, so the kill reads "1 weremoose" rather
        -- than "1 goblin". Werebeast is tested first because a figure can carry both curses --
        -- the weremoose in this world is a necromancer too -- and the beast form is the notable one.
        local wef = were_effect(vhf)
        if wef then
            local sing, plur = were_form_name(wef)
            bump(weres, sing or 'werebeast', plur or 'werebeasts', n)
            return
        end
        if cursed_as(vhf, 'Vampire') then
            local sing, plur = cursed_label(rid, 'vampire')
            bump(vamps, sing, plur, n)
            return
        end
        -- NOT the "Raised <name>" curses (bitter corpse, death stalker, ...): those are undead a
        -- necromancer raised, not necromancers themselves, and they keep counting as their race
        if cursed_as(vhf, 'Necromancer') then
            local sing, plur = cursed_label(rid, 'necromancer')
            bump(necros, sing, plur, n)
            return
        end
        local cr = df.global.world.raws.creatures.all[rid]
        local cat = classify_race(rid)
        if CAT_PLURAL[cat] then
            cats[cat] = (cats[cat] or 0) + n
            return
        elseif cat == 'megabeast' or cat == 'beast' then
            -- each megabeast TYPE is its own entry, named from its race
            if cr then
                bump(cat == 'megabeast' and megas or beasts,
                    tostring(cr.name[0]), tostring(cr.name[1]), n)
            else
                other = other + n
            end
            return
        end
        if not (cr and cr.caste[0]) then
            other = other + n
            return
        end
        -- sentient (can learn or speak) kills group by CASTE NAME: gender castes
        -- share their species' name, so "30 goblins" stays "30 goblins", while
        -- special castes (ulitharid, ancient dragon, drider, thrall) split out
        local is_animal, size = animal_info(rid)
        if is_animal then
            local a = animals[rid] or {n = 0, size = size}
            a.n = a.n + n
            animals[rid] = a
        else
            local ca = caste and caste >= 0 and caste < #cr.caste and cr.caste[caste]
            if ca then
                bump(sentients, tostring(ca.caste_name[0]), tostring(ca.caste_name[1]), n)
            else
                bump(sentients, tostring(cr.name[0]), tostring(cr.name[1]), n)
            end
        end
    end
    -- named victims: one event per kill; race AND caste come from the victim's figure
    for i = 0, #k.events - 1 do
        local ev = df.history_event.find(k.events[i])
        if ev and df.history_event_hist_figure_diedst:is_instance(ev) then
            local v = df.historical_figure.find(ev.victim_hf)
            if v then add(v.race, v.caste, 1, false, v) else total = total + 1; other = other + 1 end
        else
            total = total + 1
            other = other + 1
        end
    end
    -- anonymous kill groups (killed_count already includes undead-group kills;
    -- killed_undead is a parallel per-group FLAG marking undead groups, not a count;
    -- killed_caste is the per-group caste index within the victim race)
    for i = 0, #k.killed_race - 1 do
        add(k.killed_race[i], k.killed_caste[i], k.killed_count[i],
            is_undead_group(k.killed_undead[i]))
    end
    if total == 0 then return 'Kills: 0' end
    -- the LARGEST animal species gets its own entry; all other animals fold into "other"
    local big_rid, big
    for rid, a in pairs(animals) do
        if not big or a.size > big.size or (a.size == big.size and a.n > big.n) then
            big_rid, big = rid, a
        end
    end
    for rid, a in pairs(animals) do
        if rid ~= big_rid then other = other + a.n end
    end
    local parts = {}
    local function put(n, sing, plur)
        parts[#parts + 1] = ('%d %s'):format(n, n == 1 and sing or plur)
    end
    for _, cat in ipairs({'demon', 'archangel', 'angel'}) do
        if cats[cat] and cats[cat] > 0 then put(cats[cat], cat, CAT_PLURAL[cat]) end
    end
    for _, g in ipairs(sorted_groups(megas)) do put(g.n, g.sing, g.plur) end
    for _, g in ipairs(sorted_groups(beasts)) do put(g.n, g.sing, g.plur) end
    -- vampires then necromancers, both ahead of the plain undead: they are their own kind of kill,
    -- not another body in the pile
    for _, g in ipairs(sorted_groups(vamps)) do put(g.n, g.sing, g.plur) end
    for _, g in ipairs(sorted_groups(necros)) do put(g.n, g.sing, g.plur) end
    if cats.undead and cats.undead > 0 then put(cats.undead, 'undead', 'undead') end
    -- werecreatures ahead of the ordinary sentient kills: a weremoose is a monster you fought,
    -- not another body in the goblin count
    for _, g in ipairs(sorted_groups(weres)) do put(g.n, g.sing, g.plur) end
    for _, g in ipairs(sorted_groups(sentients)) do put(g.n, g.sing, g.plur) end
    if big then
        local cr = df.global.world.raws.creatures.all[big_rid]
        put(big.n, tostring(cr.name[0]), tostring(cr.name[1]))
    end
    if other > 0 then parts[#parts + 1] = ('%d other'):format(other) end
    return ('%d kill%s: %s'):format(total, total == 1 and '' or 's', table.concat(parts, ', '))
end

-- ---- metal + weapon/armor preference + combat stance ------------------------
-- "Prefers steel and short swords; likes combat (+23)". The preference `type`
-- enum is inline (no df.preference_type export): LikeMaterial = 0, LikeItem = 4.
-- A weapon/armor preference's item_type indexes one of the itemdef lists below;
-- the metal preference is a LikeMaterial on an INORGANIC (mattype 0) whose
-- material is a metal. Shown for any unit with a soul (not just citizens), so
-- it works on the adventure-mode unit sheet too.

local PREF_MATERIAL, PREF_ITEM = 0, 4

-- item_type -> the itemdef list holding that gear's subtypes (weapons + armour pieces)
local function gear_lists()
    local r = df.global.world.raws.itemdefs
    return {
        [df.item_type.WEAPON] = r.weapons,
        [df.item_type.ARMOR]  = r.armor,
        [df.item_type.SHOES]  = r.shoes,
        [df.item_type.SHIELD] = r.shields,
        [df.item_type.HELM]   = r.helms,
        [df.item_type.GLOVES] = r.gloves,
        [df.item_type.PANTS]  = r.pants,
    }
end

-- how the unit feels about combat: the MARTIAL_PROWESS personal value, in the
-- bands embark-prep uses (no entry in personality.values = civ default = 0)
local function combat_stance(soul)
    local strength = 0
    for _, v in ipairs(soul.personality.values) do
        if v.type == df.value_type.MARTIAL_PROWESS then
            strength = v.strength
            break
        end
    end
    local word = strength >= 41 and 'loves' or strength >= 15 and 'likes'
        or strength <= -41 and 'hates' or strength <= -15 and 'dislikes'
        or 'indifferent to'
    return ('%s combat (%+d)'):format(word, strength)
end

-- first preferred metal + first preferred weapon/armour piece + combat stance,
-- all on one line; nil only when the unit has no soul
local function prefs_line(u)
    local soul = u.status and u.status.current_soul
    if not soul then return end
    local metal, gear, lists
    for _, p in ipairs(soul.preferences) do
        if not metal and p.type == PREF_MATERIAL and p.mattype == 0 then
            local mi = dfhack.matinfo.decode(p.mattype, p.matindex)
            if mi and mi.material and mi.material.flags.IS_METAL then
                local nm = mi.material.state_name.Solid
                metal = (nm and #nm > 0) and nm or mi:toString()
            end
        elseif not gear and p.type == PREF_ITEM then
            lists = lists or gear_lists()
            local lst = lists[p.item_type]
            if lst and p.item_subtype >= 0 and p.item_subtype < #lst then
                local d = lst[p.item_subtype]
                if d then gear = (d.name_plural ~= '' and d.name_plural) or d.name end
            end
        end
        if metal and gear then break end
    end
    local pref
    if metal and gear then pref = ('Prefers %s and %s'):format(metal, gear)
    elseif metal or gear then pref = ('Prefers %s'):format(metal or gear) end
    local combat = combat_stance(soul)
    if pref then return pref .. '; ' .. combat end
    return (combat:gsub('^%l', string.upper))   -- combat alone: "Likes combat (+23)"
end

-- ---- weight + volume --------------------------------------------------------
-- "Weighs 3.1 dwarves, is 60dm^3". size_info.size_cur is cubic centimeters / 10
-- (so dm^3 = size_cur / 100); the dwarf figure matches gui/unit-info-viewer's
-- comparison against an average 6000 dwarf.

local DWARF_SIZE = 6000

-- fixed-point with just enough decimals, trailing zeros trimmed: 60, 6, 3.1, 0.08
local function fmt_num(v)
    local prec = v >= 10 and 0 or v >= 1 and 1 or v >= 0.01 and 2 or 4
    local s = ('%.' .. prec .. 'f'):format(v)
    return s:find('%.') and (s:gsub('%.?0+$', '')) or s
end

local function size_line(u)
    local sz = u.body.size_info.size_cur
    if not sz or sz <= 0 then return end
    local dwarves = fmt_num(sz / DWARF_SIZE)
    return ('Weighs %s %s, is %sdm^3'):format(
        dwarves, dwarves == '1' and 'dwarf' or 'dwarves', fmt_num(sz / 100))
end

-- description [+ weight/volume] [+ prefs & combat stance, souled units] + kills line for the selected creature, or nil
local function unit_info()
    local u = dfhack.gui.getSelectedUnit(true)
    if not u then return end
    local cr = df.global.world.raws.creatures.all[u.race]
    local caste = cr and cr.caste[u.caste]
    if not (caste and caste.description and #caste.description > 0) then return end
    local lines = {caste.description}
    local ok_sz, sz = pcall(size_line, u)
    if ok_sz and sz then lines[#lines + 1] = sz end
    local ok_pref, pref = pcall(prefs_line, u)
    if ok_pref and pref then lines[#lines + 1] = pref end
    local ok, kills = pcall(kill_summary, u)
    lines[#lines + 1] = ok and kills or 'Kills: ?'
    return table.concat(lines, '\n')
end

-- how many display rows the text needs after word-wrapping to `width`
local function wrapped_lines(text, width)
    local n = 0
    for para in (text .. '\n'):gmatch('(.-)\n') do
        local len
        for word in para:gmatch('%S+') do
            local wl = #word
            if not len then len = wl
            elseif len + 1 + wl <= width then len = len + 1 + wl
            else n = n + 1; len = wl end
        end
        n = n + 1
    end
    return n
end

-- The box's RIGHT edge is kept this many columns in from the screen's right border, so it lands
-- just left of the native creature window (at the 'u' in "powerful" on the reference bunny, where
-- W=150 -> right edge col 51) and never overlaps it. Width is recomputed from the live screen width
-- each frame, so the right edge tracks the border 1:1 -- screen one wider => box one wider, and so on.
local RIGHT_MARGIN = 98
local MIN_W = 20            -- floor so the box never collapses on a very narrow screen

CreatureDescOverlay = defclass(CreatureDescOverlay, overlay.OverlayWidget)
CreatureDescOverlay.ATTRS{
    desc = "Shows the selected creature's description in the bottom-left.",
    default_pos = {x = 3, y = -4},   -- bottom-left
    default_enabled = true,
    viewscreens = {'dwarfmode/ViewSheets/UNIT', 'dungeonmode/ViewSheets/UNIT'},
    frame = {w = 90, h = 12},
    version = 1,
    overlay_onupdate_max_freq_seconds = 0,
}

function CreatureDescOverlay:init()
    self:addviews{
        widgets.Panel{
            view_id = 'panel',
            frame = {t = 0, l = 0, r = 0, b = 0},
            frame_style = gui.FRAME_THIN,
            frame_background = gui.CLEAR_PEN,
            subviews = {
                widgets.WrappedLabel{
                    view_id = 'desc',
                    frame = {t = 0, l = 0, r = 0, b = 0},
                    text_to_wrap = '',
                    text_pen = COLOR_YELLOW,
                },
            },
        },
    }
end

-- Panels that TAKE THE SCREEN while the unit sheet is merely still open behind them. DF keeps
-- `dwarfmode/ViewSheets/UNIT` in the focus list the whole time one of these is up, so the
-- overlay is asked to draw and lands on top of somebody else's window -- the squad
-- fill-position list, say, with this box printed across the bottom of it.
--
-- Tested on the FOCUS STRINGS, not on the panels' own fields. `unit_selector.context` looks
-- like the obvious flag and is a trap: it keeps the last context it was used with long after
-- the selector has closed (SQUAD_FILL_POSITION still sitting there with nothing on screen), so
-- reading it hid this box permanently. The focus list says what is actually being drawn.
--
-- The list is by name because there is no general "is my panel in front" flag, and the focus
-- strings are NOT ordered front-to-back -- the sheet's own comes first while the selector is
-- over it. Add to it if another panel is found drawing over this corner.
local COVERING = {'/UnitSelector', '/ImageCreator', '/LocationDetails'}

local function covered()
    local ok, focus = pcall(dfhack.gui.getFocusStrings, dfhack.gui.getDFViewscreen(true))
    if not ok or not focus then return false end
    for _, f in ipairs(focus) do
        for _, pattern in ipairs(COVERING) do
            if f:find(pattern, 1, true) then return true end
        end
    end
    return false
end

function CreatureDescOverlay:overlay_onupdate()
    if covered() then self.visible = false; return end
    local text = unit_info()
    self.visible = text ~= nil
    if not text then return end
    local changed = false
    if text ~= self.subviews.desc.text_to_wrap then
        self.subviews.desc.text_to_wrap = text
        changed = true
    end
    local sw, sh = dfhack.screen.getWindowSize()
    -- in adventure mode the box's LEFT border sits 10 columns further right; the
    -- overlay anchor can't move per-mode, so the inner panel is indented instead
    local indent = dfhack.world.isAdventureMode() and 10 or 0
    local panel = self.subviews.panel
    if (panel.frame.l or 0) ~= indent then panel.frame.l = indent; changed = true end
    -- width tracks the screen so the RIGHT edge stays RIGHT_MARGIN cols in from the border (just
    -- left of the native creature window); the left edge (frame.l) stays put
    local w = math.max(MIN_W, sw - RIGHT_MARGIN - (self.frame.l or 0))
    if self.frame.w ~= w then self.frame.w = w; changed = true end
    -- grow the box to fit the wrapped text (incl. the Kills line), so nothing is
    -- cut off; cap so it stays on screen
    local h = math.max(4, math.min(wrapped_lines(text, self.frame.w - indent - 2) + 2, sh - 6))
    if self.frame.h ~= h then self.frame.h = h; changed = true end
    if changed then self:updateLayout() end
end

OVERLAY_WIDGETS = {desc = CreatureDescOverlay}

if dfhack_flags.module then
    return
end

require('plugins.overlay').rescan()
print('creature-description: registered overlay creature-description.desc')
